---
output: pdf_document
---

```{r}

library(readr)
library(ggplot2)

```

```{r}

# read in data
re <- read_csv("./realEstate.csv")

# get rid of useless columns
re <- re[,c(-(1:4),-7,-8,-12,-18,-(27:29),-(31:68))]

# remove observations with missing data
re <- na.omit(re)

# make better var names
names(re) <- gsub(" ","", names(re))

# remove unit labels and dollar signs
re$Price <- parse_number(re$Price)
re$SqrFt <- parse_number(re$SqrFt)

inSqft <- rep(NA,length(re$LotSize))
for (i in 1:length(re$LotSize)) {
  if (grepl("sqft",re$LotSize[i],fixed=TRUE)) {
    inSqft[i] <- TRUE
  } else {
    inSqft[i] <- FALSE
  }
}
re$LotSize <- parse_number(re$LotSize)
for (i in 1:length(re$LotSize)) {
  if (inSqft[i]) {
    re$LotSize[i] <- re$LotSize[i]*(1/43560)
  }
}

re$Bath <- as.factor(re$Bath)
re$Beds <- as.factor(re$Beds)

re$LastSoldFor <- parse_number(re$LastSoldFor)
re$LastTaxAssestment <- parse_number(re$LastTaxAssestment)
re$PriceSqrFt <- parse_number(re$PriceSqrFt)

```

# Potential Subsets

```{r}

# homes in Colorado, California, Denver, 80219
ca <- re[re$State == "CA",]
co <- re[re$State == "CO",]
den <- re[re$City == "Denver",]
zip80219 <- re[re$Zipcode == 80219,]

#unique(ca$Zipcode)
#unique(co$Zipcode)
#unique(den$Zipcode)
#unique(re$city)
#unique(re$State)

```

# Visualize Relationships

```{r}

# Square Ft.

ggplot(data=re,aes(x=SqrFt,y=Price)) +
  geom_point()

ggplot(data=re[-9907,],aes(x=SqrFt,y=Price)) +
  geom_point()

# Longitude and Latitude

ggplot(data=re,aes(x=Longitude,y=Price)) +
  geom_point()

ggplot(data=re,aes(x=Latitude,y=Price)) +
  geom_point()

# Lot Size (acres)

ggplot(data=re,aes(x=LotSize,y=Price)) +
  geom_point()

ggplot(data=re[c(-8769,-7483),],aes(x=LotSize,y=Price)) +
  geom_point()

# Beds and Baths

ggplot(data=re,aes(x=Beds,y=Price)) +
  geom_point()

ggplot(data=re,aes(x=Bath,y=Price)) +
  geom_point()

# Year Built

ggplot(data=re,aes(x=YearBuilt,y=Price)) +
  geom_point()

# Price Square Ft.

ggplot(data=re,aes(x=PriceSqrFt,y=Price)) +
  geom_point()

ggplot(data=re[c(-8025,-3089,-5990),],aes(x=PriceSqrFt,y=Price)) +
  geom_point()

# Last Sold Year

ggplot(data=re,aes(x=LastSoldYear,y=Price)) +
  geom_point()

# Last Sold For

ggplot(data=re,aes(x=LastSoldFor,y=Price)) +
  geom_point()

# Last Tax Assestment

ggplot(data=re,aes(x=LastTaxAssestment,y=Price)) +
  geom_point()

# Last Tax Year

ggplot(data=re,aes(x=LastTaxYear,y=Price)) +
  geom_point()

```

# Transformations

```{r}

# Transformations



```

# Code for Appendix (if needed for slides and stuff)

```{r show-code, ref.label = all_labels(), echo = TRUE, eval = FALSE}

```
