---
title: "Housing Price Prediction from Trulia.com Data"
author: "Sam Fortescue, Mark Gardner, Nat Koonmee"
date: "12/06/21"
output: slidy_presentation
---

```{r, include=FALSE}

# PACKAGES AND DEPENDENT CODE FROM CODE.RMD

library(readr)
library(ggplot2)
library(leaps)
library(glmnet)
library(car)
library(pls)
library(dplyr)

```

```{r, include=FALSE}

# read in data
re <- read_csv("./realEstate.csv")

# get rid of useless columns
re <- re[,c(-(1:4),-7,-8,-12,-18,-(27:29),-(31:68))]

# remove observations with missing data
re <- na.omit(re)

# make better var names
names(re) <- gsub(" ","", names(re))

# remove unit labels and dollar signs
re$Price <- parse_number(re$Price)
re$SqrFt <- parse_number(re$SqrFt)

inSqft <- rep(NA,length(re$LotSize))
for (i in 1:length(re$LotSize)) {
  if (grepl("sqft",re$LotSize[i],fixed=TRUE)) {
    inSqft[i] <- TRUE
  } else {
    inSqft[i] <- FALSE
  }
}
re$LotSize <- parse_number(re$LotSize)
for (i in 1:length(re$LotSize)) {
  if (inSqft[i]) {
    re$LotSize[i] <- re$LotSize[i]*(1/43560)
  }
}

re$Bath <- as.factor(re$Bath)
re$Beds <- as.factor(re$Beds)

re$LastSoldFor <- parse_number(re$LastSoldFor)
re$LastTaxAssestment <- parse_number(re$LastTaxAssestment)
re$PriceSqrFt <- parse_number(re$PriceSqrFt)

```

```{r, include=FALSE}

ca <- re[re$State == "CA",c(-1,-10,-15)]
co <- re[re$State == "CO",c(-1,-10,-15)]
la <- re[re$City == "Los Angeles",c(-1,-10,-15)]
den <- re[re$City == "Denver",c(-1,-10,-15)]

```

```{r, include=FALSE}

ca_t <- ca[,c(-7,-14,-15)]
ca_t$Price <- log(ca_t$Price)
ca_t$SqrFt <- sqrt(ca_t$SqrFt)
ca_t$LotSize <- log(ca_t$LotSize)
ca_t$LastSoldFor <- log(ca_t$LastSoldFor)
ca_t$LastTaxAssestment <- log(ca_t$LastTaxAssestment)
ca_t$LastTaxYear <- as.factor(ca_t$LastTaxYear)

co_t <- co[,c(-12,-14,-15)]
co_t$Price <- log(co_t$Price)
co_t$SqrFt <- sqrt(co_t$SqrFt)
co_t$LotSize <- log(co_t$LotSize)
co_t$LastSoldFor <- log(co_t$LastSoldFor)
co_t$LastTaxAssestment <- log(co_t$LastTaxAssestment)

la_t <- la[,c(-7,-13,-14,-15)]
la_t$Price <- log(la_t$Price)
la_t$SqrFt <- sqrt(la_t$SqrFt)
la_t$LotSize <- log(la_t$LotSize)
la_t$LastSoldFor <- log(la_t$LastSoldFor)
la_t$LastTaxAssestment <- log(la_t$LastTaxAssestment)
la_t$LastTaxYear <- as.factor(la_t$LastTaxYear)

den_t <- den[,c(-12,-13,-14,-15)]
den_t$Price <- log(den_t$Price)
den_t$SqrFt <- sqrt(den_t$SqrFt)
den_t$LotSize <- log(den_t$LotSize)
den_t$LastSoldFor <- log(den_t$LastSoldFor)
den_t$LastTaxAssestment <- log(den_t$LastTaxAssestment)

```

```{r,include=FALSE}

k <- 10
lambda <- 10^seq(-4,10,length.out=1000)

set.seed(420)

# California

n <- nrow(ca_t)
trn <- seq_len(n) %in% sample(seq_len(n),round(0.7*n))

n <- length(trn[trn==TRUE])
folds <- sample(seq_len(k), n, replace = k != n)

## Base Model

base_lm_ca <- lm(Price~.,data=ca_t[trn,c(-6,-12)])
aliasMatrixCA <- alias(base_lm_ca)$Complete
vif(base_lm_ca)

pred_base_ca <- predict(base_lm_ca,ca_t[!trn,c(-6,-12)])
mse_base_ca <- mean((ca_t[!trn,c(-6,-12)]$Price - pred_base_ca)^2)

## Ridge

cv_ridge_ca <- cv.glmnet(model.matrix(Price~.,data=ca_t)[trn,-1],unlist(ca_t[trn,1]),alpha=0,lambda=lambda,foldid=folds)

ridge_trn_ca <- glmnet(model.matrix(Price~.,data=ca_t)[trn,-1],unlist(ca_t[trn,1]),alpha=0,lambda=cv_ridge_ca$lambda.min)
pred_ridge_ca <- predict(ridge_trn_ca, model.matrix(Price~.,data=ca_t)[!trn,-1])

mse_ridge_ca <- mean((ca_t[!trn,]$Price - pred_ridge_ca)^2)

## Lasso

cv_lasso_ca <- cv.glmnet(model.matrix(Price~.,data=ca_t)[trn,-1],unlist(ca_t[trn,1]),alpha=1,lambda=lambda,foldid=folds)

lasso_trn_ca <- glmnet(model.matrix(Price~.,data=ca_t)[trn,-1],unlist(ca_t[trn,1]),alpha=1,lambda=cv_lasso_ca$lambda.min)
pred_lasso_ca <- predict(lasso_trn_ca, model.matrix(Price~.,data=ca_t)[!trn,-1])

mse_lasso_ca <- mean((ca_t[!trn,]$Price - pred_lasso_ca)^2)

## PCR

cv_pcr_ca <- pcr(Price ~ ., data = ca_t[trn,c(-6,-7,-12,-13)], validation = "CV", scale=TRUE, segments=cvsegments(nrow(ca_t[trn,]),10))
mse_cv <- MSEP(cv_pcr_ca)
M <- mse_cv$comps[which.min(as.data.frame(mse_cv$val)[1,])]

pcr_trn_ca <- pcr(Price ~., data = ca_t[trn,c(-6,-7,-12,-13)], scale=TRUE, M=M)
pred_pcr_ca <- predict(pcr_trn_ca, model.matrix(Price ~ .,data=ca_t[,c(-6,-7,-12,-13)])[!trn,-1])

mse_pcr_ca <- mean((ca_t[!trn,]$Price - pred_pcr_ca)^2)

## PLS

cv_pls_ca <- plsr(Price ~ ., data = ca_t[trn, c(-6,-7,-12,-13)], validation = "CV", scale=TRUE,segments=cvsegments(nrow(ca_t[trn,]),10))
mse_cv <- MSEP(cv_pls_ca)
M <- mse_cv$comps[which.min(as.data.frame(mse_cv$val)[1,])]

pls_trn_ca <- plsr(Price ~., data = ca_t[trn,c(-6,-7,-12,-13)], scale=TRUE, M=M)
pred_pls_ca <- predict(pls_trn_ca, model.matrix(Price ~ .,data=ca_t[,c(-6,-7,-12,-13)])[!trn,-1])

mse_pls_ca <- mean((ca_t[!trn,]$Price - pred_pls_ca)^2)

# Colorado

n <- nrow(co_t)
trn <- seq_len(n) %in% sample(seq_len(n),round(0.7*n))

n <- length(trn[trn==TRUE])
folds <- sample(seq_len(k), n, replace = k != n)

## Base Model

base_lm_co <- lm(Price~.,data=co_t[trn,c(-6,-7,-12)])
aliasMatrixCO <- alias(base_lm_co)$Complete
vif(base_lm_co)

pred_base_co <- predict(base_lm_co,co_t[!trn,c(-6,-7,-12)])
mse_base_co <- mean((co_t[!trn,c(-6,-7,-12)]$Price - pred_base_co)^2)

## Ridge

cv_ridge_co <- cv.glmnet(model.matrix(Price~.,data=co_t)[trn,-1],unlist(co_t[trn,1]),alpha=0,lambda=lambda,foldid=folds)

ridge_trn_co <- glmnet(model.matrix(Price~.,data=co_t)[trn,-1],unlist(co_t[trn,1]),alpha=0,lambda=cv_ridge_co$lambda.min)
pred_ridge_co <- predict(ridge_trn_co, model.matrix(Price~.,data=co_t)[!trn,-1])

mse_ridge_co <- mean((co_t[!trn,]$Price - pred_ridge_co)^2)

## Lasso

cv_lasso_co <- cv.glmnet(model.matrix(Price~.,data=co_t)[trn,-1],unlist(co_t[trn,1]),alpha=1,lambda=lambda,foldid=folds)

lasso_trn_co <- glmnet(model.matrix(Price~.,data=co_t)[trn,-1],unlist(co_t[trn,1]),alpha=1,lambda=cv_lasso_co$lambda.min)
pred_lasso_co <- predict(lasso_trn_co, model.matrix(Price~.,data=co_t)[!trn,-1])

mse_lasso_co <- mean((co_t[!trn,]$Price - pred_lasso_co)^2)

## PCR

cv_pcr_co <- pcr(Price ~ ., data = co_t[trn,c(-6,-7,-12)], validation = "CV", scale=TRUE, segments=cvsegments(nrow(co_t[trn,]),10))
mse_cv <- MSEP(cv_pcr_co)
M <- mse_cv$comps[which.min(as.data.frame(mse_cv$val)[1,])]

pcr_trn_co <- pcr(Price ~., data = co_t[trn,c(-6,-7,-12,-13)], scale=TRUE, M=M)
pred_pcr_co <- predict(pcr_trn_co, model.matrix(Price ~ .,data=co_t[,c(-6,-7,-12,-13)])[!trn,-1])

mse_pcr_co <- mean((co_t[!trn,]$Price - pred_pcr_co)^2)

## PLS

cv_pls_co <- plsr(Price ~ ., data = co_t[trn, c(-6,-7,-12)], validation = "CV", scale=TRUE,segments=cvsegments(nrow(co_t[trn,]),10))
mse_cv <- MSEP(cv_pls_co)
M <- mse_cv$comps[which.min(as.data.frame(mse_cv$val)[1,])]

pls_trn_co <- plsr(Price ~., data = co_t[trn,c(-6,-7,-12)], scale=TRUE, M=M)
pred_pls_co <- predict(pls_trn_co, model.matrix(Price ~ .,data=co_t[,c(-6,-7,-12)])[!trn,-1])

mse_pls_co <- mean((co_t[!trn,]$Price - pred_pls_co)^2)

# Los Angeles

n <- nrow(la_t)
trn <- seq_len(n) %in% sample(seq_len(n),round(0.7*n))

n <- length(trn[trn==TRUE])
folds <- sample(seq_len(k), n, replace = k != n)

## Base Model

base_lm_la <- lm(Price~.,data=la_t[trn,c(-6,-11)])
aliasMatrixLA <- alias(base_lm_la)$Complete
vif(base_lm_la)

pred_base_la <- predict(base_lm_la,la_t[!trn,c(-6,-11)])
mse_base_la <- mean((la_t[!trn,c(-6,-12)]$Price - pred_base_la)^2)

## Ridge

cv_ridge_la <- cv.glmnet(model.matrix(Price~.,data=la_t)[trn,-1],unlist(la_t[trn,1]),alpha=0,lambda=lambda,foldid=folds)

ridge_trn_la <- glmnet(model.matrix(Price~.,data=la_t)[trn,-1],unlist(la_t[trn,1]),alpha=0,lambda=cv_ridge_la$lambda.min)
pred_ridge_la <- predict(ridge_trn_la, model.matrix(Price~.,data=la_t)[!trn,-1])

mse_ridge_la <- mean((la_t[!trn,]$Price - pred_ridge_la)^2)

## Lasso

cv_lasso_la <- cv.glmnet(model.matrix(Price~.,data=la_t)[trn,-1],unlist(la_t[trn,1]),alpha=1,lambda=lambda,foldid=folds)

lasso_trn_la <- glmnet(model.matrix(Price~.,data=la_t)[trn,-1],unlist(la_t[trn,1]),alpha=1,lambda=cv_lasso_la$lambda.min)
pred_lasso_la <- predict(lasso_trn_la, model.matrix(Price~.,data=la_t)[!trn,-1])

mse_lasso_la <- mean((la_t[!trn,]$Price - pred_lasso_la)^2)

## PCR

cv_pcr_la <- pcr(Price ~ ., data = la_t[trn,c(-6,-11)], validation = "CV", scale=TRUE, segments=cvsegments(nrow(la_t[trn,]),10))
mse_cv <- MSEP(cv_pcr_la)
M <- mse_cv$comps[which.min(as.data.frame(mse_cv$val)[1,])]

pcr_trn_la <- pcr(Price ~., data = la_t[trn,c(-6,-11)], scale=TRUE, M=M)
pred_pcr_la <- predict(pcr_trn_la, model.matrix(Price ~ .,data=la_t[,c(-6,-11)])[!trn,-1])

mse_pcr_la <- mean((la_t[!trn,]$Price - pred_pcr_la)^2)

## PLS

cv_pls_la <- plsr(Price ~ ., data = la_t[trn, c(-6,-11)], validation = "CV", scale=TRUE,segments=cvsegments(nrow(la_t[trn,]),10))
mse_cv <- MSEP(cv_pls_la)
M <- mse_cv$comps[which.min(as.data.frame(mse_cv$val)[1,])]

pls_trn_la <- plsr(Price ~., data = la_t[trn,c(-6,-11)], scale=TRUE, M=M)
pred_pls_la <- predict(pls_trn_la, model.matrix(Price ~ .,data=la_t[,c(-6,-11)])[!trn,-1])

mse_pls_la <- mean((la_t[!trn,]$Price - pred_pls_la)^2)

# Denver

n <- nrow(den_t)
trn <- seq_len(n) %in% sample(seq_len(n),round(0.7*n))

n <- length(trn[trn==TRUE])
folds <- sample(seq_len(k), n, replace = k != n)

## Base Model

base_lm_den <- lm(Price~.,data=den_t[trn,c(-6,-7)])
aliasMatrixDEN <- alias(base_lm_den)$Complete
vif(base_lm_den)

pred_base_den <- predict(base_lm_den,den_t[!trn,c(-6,-7)])
mse_base_den <- mean((den_t[!trn,c(-6,-7)]$Price - pred_base_den)^2)

## Ridge

cv_ridge_den <- cv.glmnet(model.matrix(Price~.,data=den_t)[trn,-1],unlist(den_t[trn,1]),alpha=0,lambda=lambda,foldid=folds)

ridge_trn_den <- glmnet(model.matrix(Price~.,data=den_t)[trn,-1],unlist(den_t[trn,1]),alpha=0,lambda=cv_ridge_co$lambda.min)
pred_ridge_den <- predict(ridge_trn_den, model.matrix(Price~.,data=den_t)[!trn,-1])

mse_ridge_den <- mean((den_t[!trn,]$Price - pred_ridge_den)^2)

## Lasso

cv_lasso_den <- cv.glmnet(model.matrix(Price~.,data=den_t)[trn,-1],unlist(den_t[trn,1]),alpha=1,lambda=lambda,foldid=folds)

lasso_trn_den <- glmnet(model.matrix(Price~.,data=den_t)[trn,-1],unlist(den_t[trn,1]),alpha=1,lambda=cv_lasso_co$lambda.min)
pred_lasso_den <- predict(lasso_trn_den, model.matrix(Price~.,data=den_t)[!trn,-1])

mse_lasso_den <- mean((den_t[!trn,]$Price - pred_lasso_den)^2)

## PCR

cv_pcr_den <- pcr(Price ~ ., data = den_t[trn,c(-6,-7)], validation = "CV", scale=TRUE, segments=cvsegments(nrow(den_t[trn,]),10))
mse_cv <- MSEP(cv_pcr_den)
M <- mse_cv$comps[which.min(as.data.frame(mse_cv$val)[1,])]

pcr_trn_den <- pcr(Price ~., data = den_t[trn,c(-6,-7)], scale=TRUE, M=M)
pred_pcr_den <- predict(pcr_trn_den, model.matrix(Price ~ .,data=den_t[,c(-6,-7)])[!trn,-1])

mse_pcr_den <- mean((den_t[!trn,]$Price - pred_pcr_den)^2)

## PLS

cv_pls_den <- plsr(Price ~ ., data = den_t[trn, c(-6,-7)], validation = "CV", scale=TRUE,segments=cvsegments(nrow(den_t[trn,]),10))
mse_cv <- MSEP(cv_pls_den)
M <- mse_cv$comps[which.min(as.data.frame(mse_cv$val)[1,])]

pls_trn_den <- plsr(Price ~., data = den_t[trn,c(-6,-7)], scale=TRUE, M=M)
pred_pls_den <- predict(pls_trn_den, model.matrix(Price ~ .,data=den_t[,c(-6,-7)])[!trn,-1])

mse_pls_den <- mean((den_t[!trn,]$Price - pred_pls_den)^2)

```

# About the Data



# Motivation



# Problems with the Data

Lack of Observations!

# Data Transformations for Linear Models



# Add Graph



# Linear Models



# Hypothetical Data


